name 'iot-devices'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures iot-devices'
long_description 'Installs/Configures iot-devices'
version '0.2.11'

depends 'samba', '~> 0.12.0'
depends 'ntp', '~> 1.8.6'
